name: Daily Java Interview Engine

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: '0 3 * * 1,3,4'  # Mon, Wed, Thu (8:30 AM IST)
  workflow_dispatch:

jobs:
  generate-java-skeleton:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run generator (rate-safe)
        env:
          GROQ_API_KEY: ${{ secrets.KAFKA_API_KEY }}
        run: python scripts/generate.py

      - name: Commit & Push to new branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          
          BRANCH="auto/java-daily"
          
          git checkout -B $BRANCH
          
          git add .
          
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          
          git commit -m "chore: daily java interview generation - $(date +'%Y-%m-%d')"
          git push origin $BRANCH --force